@startuml StateChartRast
hide empty description
[*] -> Aguardando
state "Programação" as prog
Aguardando --> prog
Aguardando -> Garantia
Garantia -> [*]
prog -> Oficina
state "Aguardando Teste" as At
state "Aguardando Lavagagem" as Al
state Oficina {
    state "Em etapa n" as sub
    sub -> sub : checkinSubestado (etapa += 1)
    sub --> At : [etapa >= n_etapas]

}
Oficina : etapa
Oficina : n_etapas
At --> Teste
Teste -> Al
Al ---> Lavagem
Lavagem ----> Completo
Completo -> Retirado
Retirado -> [*]
@enduml